### ISSUE TITLE
训练中RuntimeError: CUDA out of memory错误

### ISSUE THREAD

**Issue by v-yunbin** [libai3/masr#50]
Error1:
```
[1/1000][5173/35392]	Loss = 107.08069610595703
Warning: NaN or Inf found in input tensor.
[1/1000][5174/35392]	Loss = inf
[1/1000][5175/35392]	Loss = 103.25633239746094
Warning: NaN or Inf found in input tensor.
[1/1000][5176/35392]	Loss = inf
[1/1000][5177/35392]	Loss = 91.28031921386719
Warning: NaN or Inf found in input tensor.
[1/1000][5178/35392]	Loss = inf
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    train(model)
  File "train.py", line 56, in train
    for i, (x, y, x_lens, y_lens) in enumerate(train_dataloader):
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
librosa.util.exceptions.ParameterError: Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zyb/masr/data.py", line 58, in __getitem__
    spect = spectrogram(wav)
  File "/home/zyb/masr/data.py", line 31, in spectrogram
    wav, n_fft=n_fft, hop_length=hop_length, win_length=win_length, window=window
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/librosa/core/spectrum.py", line 161, in stft
    util.valid_audio(y)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/librosa/util/utils.py", line 170, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```

solved: 训练集里有空音频

**Comment by v-yunbin** [comment]
已经解决，训练集里有空音频。

**Comment by v-yunbin** [comment]
Error3:
```
[1/1000][12181/35392]	Loss = inf
[1/1000][12182/35392]	Loss = 118.1401138305664
[1/1000][12183/35392]	Loss = 83.45428466796875
[1/1000][12184/35392]	Loss = 83.31060791015625
[1/1000][12185/35392]	Loss = 89.13545989990234
[1/1000][12186/35392]	Loss = 97.50189208984375
[1/1000][12187/35392]	Loss = 101.6380844116211
[1/1000][12188/35392]	Loss = 102.50827026367188
[1/1000][12189/35392]	Loss = 81.79352569580078
[1/1000][12190/35392]	Loss = 83.26094818115234
[1/1000][12191/35392]	Loss = 88.23612213134766
[1/1000][12192/35392]	Loss = 86.24215698242188
[1/1000][12193/35392]	Loss = 87.46318054199219
Warning: NaN or Inf found in input tensor.
[1/1000][12194/35392]	Loss = inf
[1/1000][12195/35392]	Loss = 76.48516845703125
[1/1000][12196/35392]	Loss = 82.52027130126953
[1/1000][12197/35392]	Loss = 73.47178649902344
[1/1000][12198/35392]	Loss = 75.05223846435547
[1/1000][12199/35392]	Loss = 67.87295532226562
Traceback (most recent call last):
  File "train_fix.py", line 121, in <module>
    train(model)
  File "train_fix.py", line 58, in train
    out, out_lens = model(x, x_lens)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyb/masr/models/conv.py", line 50, in forward
    x = self.cnn(x)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyb/masr/models/conv.py", line 18, in forward
    x = self.conv(x)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 582.00 MiB (GPU 0; 7.92 GiB total capacity; 5.67 GiB already allocated; 209.00 MiB free; 1.55 GiB cached)
```

**Comment by v-yunbin** [comment]
Error4：
```
357it [01:31,  4.50it/s]
358it [01:31,  4.14it/s]
359it [01:32,  3.89it/s]
360it [01:32,  3.85it/s]
361it [01:32,  4.05it/s]
362it [01:32,  4.12it/s]
363it [01:32,  4.33it/s]
364it [01:33,  4.12it/s]Traceback (most recent call last):
  File "train_fix.py", line 124, in <module>
    train(model)
  File "train_fix.py", line 80, in train
    cer = eval(model, dev_dataloader)
  File "train_fix.py", line 112, in eval
    cer += decoder.cer(trans, ref) / float(len(ref))
ZeroDivisionError: float division by zero
```

**Comment by v-yunbin** [comment]
训练log:
[1/1000][18377/35392]	Loss = 8.876114845275879
[1/1000][18378/35392]	Loss = 7.887100696563721
[1/1000][18379/35392]	Loss = 8.926383018493652
[1/1000][18380/35392]	Loss = 5.814878463745117
[1/1000][18381/35392]	Loss = 8.963436126708984
[1/1000][18382/35392]	Loss = 6.298241138458252
[1/1000][18383/35392]	Loss = 9.845922470092773
[1/1000][18384/35392]	Loss = 7.071393966674805
[1/1000][18385/35392]	Loss = 6.255049705505371

**Comment by libai3** [comment]
Well, It seems the loss gets that low within one epoch.
What's your batch size?

**Comment by jldeng3** [comment]
change the batch-size of small ,i solve it

**Comment by baicaitongee** [comment]
> Well, It seems the loss gets that low within one epoch.
> What's your batch size?

Hello,i have post it to raspberry pi ,but in the end i get an error :Cannot allocate memory mmap failed for size 2953349384 at offset 0, i have post an #135 ,please check it when you free,thanks!
